<?php
/**
 * Copyright (c) VCT. All rights reserved
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Vct\Main\Block\Adminhtml\System\Config\Links;

/** @var Escaper $escaper */
/** @var Template $block */
$email = 'mailto:vct.vendor@gmail.com';
$supportInfos = $block->getData(Links::SUPPORT_INFO);
$supportParams = urlencode(implode(' | ', $supportInfos));
$supportUrl = sprintf('%s?subject=Support&body=%s', $email, $supportParams);
?>
<div class="vct-header">
    <div class="vct-links">
        <a href="https://commercemarketplace.adobe.com/partner/VCT#partner.products.info" target="_blank">
            <img src="https://raw.githubusercontent.com/vct-vendor/vct-vendor.github.io/master/static/img/logo.svg" />
        </a>
        <a href="https://vct-vendor.github.io" target="_blank">
            <?= $escaper->escapeHtml(__('Docs')->render()) ?>
        </a>
        <a href="https://vct-vendor.github.io/faq" target="_blank">
            <?= $escaper->escapeHtml(__('FAQ')->render()) ?>
        </a>
        <a href="<?= $escaper->escapeUrl($supportUrl) ?>" target="_blank">
            <?= $escaper->escapeHtml(__('Support')->render()) ?>
        </a>
        <a href="<?= $escaper->escapeUrl($email) ?>" target="_blank" class='feature-request'>
            <?= $escaper->escapeHtml(__('Feature Request')->render()) ?>
        </a>
    </div>

    <div class="vct-support-info">
        <?php foreach ($supportInfos as $supportInfo): ?>
            <span><?= $escaper->escapeHtml($supportInfo) ?></span>
        <?php endforeach ?>
    </div>
</div>
